config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :wines do
    resources :bottles
    collection do
      match 'search' => 'wines#index', via: [:get, :post], as: :search
    end
  end
  root to: 'wines#index'

  put 'bottles/:id/drink' => 'bottles#drink', as: :bottles_drink

  get 'welcome/index'

end

app/models/bottle.rb
class Bottle < ActiveRecord::Base
  belongs_to :wine
  accepts_nested_attributes_for :wine, :update_only => true

  UNRANSACKABLE_ATTRIBUTES = %w[id created_at updated_at wine_id]
  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :wines
  has_many :bottles, through: :wines
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  has_many :bottles, :dependent => :destroy
  belongs_to :user

  paginates_per 12

  before_validation :set_vintage_nonvintage

  after_validation :drink_by_cannot_be_greater_than_or_equal_to_vintage

  validates :vintage, :maturity, :drink_by,
            numericality: {only_integer: true, greater_than: 1899, less_than: 2101, allow_blank: true}

  validate :maturity_cannot_be_greater_than_or_equal_to_vintage

  validate :drink_by_cannot_be_greater_than_or_equal_to_vintage

  def maturity_cannot_be_greater_than_or_equal_to_vintage
    if vintage.present? && maturity.present? && maturity < vintage
      errors.add(:vintage, "can't be later than maturity")
    end
  end

  def drink_by_cannot_be_greater_than_or_equal_to_vintage
    if vintage.present? && drink_by.present? && drink_by < vintage
      errors.add(:vintage, "can't be later than drink_by")
    end
  end

  UNRANSACKABLE_ATTRIBUTES = %w[id created_at updated_at]
  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end

  def set_vintage_nonvintage
    self.vintage = nil
    self.non_vintage = nil
    if self.vintage_displayer.nil? || self.vintage_displayer == ""
      self.non_vintage = nil
      self.vintage = nil
    elsif self.vintage_displayer.is_a? String and ["NV", "NON VINTAGE", "NON-VINTAGE"].include? self.vintage_displayer.upcase
      self.non_vintage = true
      self.vintage_displayer = "NV"
    else
      vintage = Integer(self.vintage_displayer) rescue nil
      if !vintage.nil?
        if vintage > 1899 && vintage < 2101
          self.non_vintage = false
          self.vintage = vintage
          self.vintage_displayer = vintage.to_s
        else
          errors.add(:vintage, "can't be before 1900 or after 2100")
        end
      else
        errors.add(:vintage, "illegal value for vintage")
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController

  helper :wines
  before_filter :authenticate_user!

  def create
    @wine = Wine.find(params[:wine_id])
    @bottles = @wine.bottles.create(bottle_params)

    redirect_to wine_path(@wine)
  end

  def destroy
    @wine = Wine.find(params[:wine_id])
    @bottle = @wine.bottles.find(params[:id])
    @bottle.destroy
    redirect_to wine_path(@wine)
  end

  def new
    @wine = Wine.find(params[:wine_id])
    @bottle = @wine.build
    @path = [@wine, @bottle]
  end

  def edit
    @bottle = Bottle.find(params[:id])
    @path = @bottle
  end

  def update
    @bottle = Bottle.find(params[:id])
    @bottle.update_attributes(bottle_params)
    redirect_to wine_path(@bottle.wine)
  end

  def drink
    @bottle = Bottle.find(params[:id])
    @bottle.location = ""
    @bottle.consumed_date = Time.zone.today
    @bottle.save
    redirect_to wine_path(@bottle.wine)
  end

  private
    def bottle_params
      params.require(:bottle).permit(:purchased_from, :purchase_price, :purchase_date, :location, :consumed_date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController

  before_filter :authenticate_user!

  def new
    @wine = Wine.new
  end

  def create
    @wine = Wine.new(wine_params)
    @wine.user_id = current_user.id

    if @wine.save
      redirect_to @wine
    else
      render 'new'
    end
  end

  def show
    @wine = current_user.wines.find(params[:id])
    @wine.vintage_displayer = @wine.set_vintage_nonvintage
    @available_bottles = Bottle.where(wine_id: @wine.id).where(consumed_date: nil)
  end

  def index
    @q = Wine.search(params[:q])
    @wines = @q.result.page(params[:page]).where(user_id: current_user.id)
    @q.build_condition if @q.conditions.empty?
    @q.build_sort if @q.sorts.empty?
  end

  def search
    # work around for is present until ransack add more positive and negative tests
    params[:q][:location_present] = "1" if
        params[:q][:location_blank].nil? ||
            params[:q][:location_blank] == "0"
    params[:q][:consumed_date_present] = "1" if
        params[:q][:consumed_date].nil?

    @q = Wine.search(params[:q])
    @wines = @q.result
    render 'index'
  end

  def update
    @wine = current_user.wines.find(params[:id])

    if @wine.update(wine_params)
      redirect_to @wine
    else
      render 'edit'
    end
  end

  def edit
    @wine = current_user.wines.find(params[:id])
  end

  def destroy
    @wine = Wine.find(params[:id])
    @wine.destroy

    redirect_to wines_path
  end

  private
    def wine_params
      params.require(:wine).permit(:winery, :variety, :color, :vintage, :appellation, :vineyard, :winemaker,
                                   :alcohol_content, :sparkling, :bottle_size, :country, :maturity, :drink_by,
                                   :dessert, :my_notes, :other_notes, :non_vintage, :vintage_displayer, :user_id,
                                    bottles_attributes: [:id, :purchased_from, :purchase_price, :location,
                                                        :purchase_date, :consumed_date, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Wine Cellar"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  # generate link_to fields
  def link_to_add_fields(name, f, type)
    new_object = f.object.send "build_#{type}"
    id = "new_#{type}"
    fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
      render(type.to_s + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

end

app/helpers/bottles_helper.rb
module BottlesHelper
  # Returns a formatted date or nil
  def date_or_nil(date)
    date.nil? ? nil : date.strftime("%x")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/bottles/_bottle.html.erb
<div class="row">
  <div class="form-horizontal col-xs-2"><%= bottle.purchased_from, :style => "color:black" %></div>
  <div class="form-horizontal col-xs-2"><%= number_to_currency(bottle.purchase_price, precision: 2) %></div>
  <div class="form-horizontal col-xs-2"><%= bottle.location, :style => "color:black" %></div>
  <div class="form-horizontal col-xs-2"><%= date_or_nil(bottle.purchase_date) %></div>
  <div class="form-horizontal col-xs-1"><%= date_or_nil(bottle.consumed_date) %></div>
  <div class="form-horizontal col-xs-1">
    <%= link_to 'Edit', [:edit, bottle.wine, bottle], method: :get, :style => "color:black" %>
  </div>
  <div class="form-horizontal col-xs-1">
    <%= link_to 'Delete', [bottle.wine, bottle], method: :delete, data: {confirm: 'Are you sure?'}, :style => "color:red" %>
  </div>
</div>

app/views/bottles/edit.html.erb
<% provide(:title, "Edit Bottle") %>
<h1 class="h4">Edit Bottle</h1>

<%= form_for ([@bottle.wine, @bottle]) do |f| %>
    <div class="row">
      <div class="form-horizontal col-xs-2"><strong>Purchased From</strong></div>
      <div class="form-horizontal col-xs-2"><strong>Price</strong></div>
      <div class="form-horizontal col-xs-2"><strong>Location</strong></div>
      <div class="form-horizontal col-xs-2"><strong>Purchased</strong></div>
      <div class="form-horizontal col-xs-2"><strong>Consumed</strong></div>
    </div>

    <div class="row">
      <div class="form-horizontal col-xs-2"><%= f.text_field :purchased_from, :style => "color:black" %></div>
      <div class="form-horizontal col-xs-2"><%= f.number_field :purchase_price, :size => "9", :maxlength => "9",
                                                               :step => 0.01, :max => 99999.99, :style => "color:black",
                                                               :precision => number_with_precision(:purchase_price, :precision => 2) %>
      </div>

      <div class="form-horizontal col-xs-2"><%= f.text_field :location, :style => "color:black" %></div>
      <div class="form-horizontal col-xs-2"><%= f.date_field :purchase_date, options = {style: "height:26px; color:black"} %></div>
      <div class="form-horizontal col-xs-2"><%= f.date_field :consumed_date, options = {style: "height:26px; color:black"} %></div>
      <br>
      <br>
    </div>


    <button type="submit" class="btn btn-default btn-primary, style = black">
      Update Bottle
      <span class="glyphicon glyphicon-glass"></span>
    </button>


    <%= link_to :back, class: "btn btn-default btn-primary, style = black" do %>
        Back
        <span class="glyphicon glyphicon-glass"></span>
    <% end %>

    <%= link_to wines_path, class: "btn btn-default btn-primary, style = black" do %>
        All Wines
        <span class="glyphicon glyphicon-glass"></span>
    <% end %>

<% end %>

app/views/bottles/show.html.erb
<h1>Show Bottle</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<header>
  <div class="container">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "Home", '#' %></li>
      <li><%= link_to "Help", '#' %></li>
    </ul>
    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
  </div>
</header>
<div class="container-fluid">
  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Wines</h1>
<%= link_to 'Wines', controller: 'wines' %>

app/views/wines/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
      <%= a.attribute_select associations: [:bottles] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
      <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/wines/_sort_fields.html.erb
<div class="field" data-object-name="<%= f.object_name %>">
  <%= f.sort_select %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/wines/edit.html.erb
<% provide(:title, "Edit Wine") %>
<h1 class="h4">Edit Wine</h1>

<%= render 'form' %>

<%= link_to wines_path, class: 'btn btn-default btn-primary, foreground = black' do %>
    All Wines
    <span class="glyphicon glyphicon-glass"></span>
<% end %>

app/views/wines/index.html.erb
<% provide(:title, "Show All Wines") %>
<h1 class="h4">Wines</h1>

<%= search_form_for @q, url: search_wines_path, html: { method: :post } do |f| %>
    <%= f.condition_fields do |c| %>
        <%= render "condition_fields", f: c %>
    <% end %>
    <p><%= link_to_add_fields "Add Conditions", f, :condition %></p>
    <div class="field">
      Sort:
      <%= f.sort_fields do |s| %>
          <%= s.sort_select %>
      <% end %>
      <%= link_to "remove", '#', class: "remove_fields" %>
    </div>
    <p><%= link_to_add_fields "Add Sort", f, :sort %></p>
    <div class="actions"><%= f.submit "Search" %></div>
<% end %>

<!--<div class="table-responsive">-->
<table id="wines" class="table table-condensed">
  <tr>
    <th><%= sort_link @q, :winery, "Winery" %></th>
    <th><%= sort_link @q, :variety, "Variety" %></th>
    <th><%= sort_link @q, :vintage, "Vintage" %></th>
    <th><%= sort_link @q, :appellation, "Appellation" %></th>
    <th><%= sort_link @q, :vineyard, "Vineyard" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <%= paginate @wines %>
  <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.winery %></td>
        <td><%= wine.variety %></td>
        <td><%= wine.vintage %></td>
        <td><%= wine.appellation %></td>
        <td><%= wine.vineyard %></td>
        <td><%= link_to 'Show', wine_path(wine) %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td>
          <%= link_to 'Delete', wine_path(wine), :style => "color:yellow",
                      method: :delete, data: {confirm: 'Delete this wine and its bottles?'} %>
        </td>
      </tr>
  <% end %>
</table>
<!--</div>-->

<%= link_to new_wine_path, class: "btn btn-default btn-primary, foreground = black" do %>
    New Wine
    <span class="glyphicon glyphicon-glass"></span>
<% end %>
<%= paginate @wines %>

app/views/wines/new.html.erb
<% provide(:title, "Add Wine") %>
<h1 class="h4">New Wine</h1>

<%= render 'form' %>

<%= link_to 'Back', wines_path %>

<!--
Looks ugly with the form
<%= link_to wines_path, class: 'btn btn-primary' do %>
    Back
    <span class="glyphicon glyphicon-glass"></span>
<% end %>
-->

app/views/wines/show.html.erb
<% provide(:title, "Show Wine") %>
<h1 class="h4">Show Wine</h1>

<div class="row">
  <div class="form-horizontal col-xs-2 text-right"><strong>Winery</strong></div>
  <div class="form-horizontal col-xs-5 text-left"><%= @wine.winery %></div>
  <div class="form-horizontal col-xs-2 text-right"><strong>Vintage</strong></div>
  <div class="form-horizontal col-xs-3 text-left"><%= @wine.vintage_displayer %></div>
</div>

<div class="row">
  <div class="form-horizontal col-xs-2 text-right"><strong>Variety</strong></div>
  <div class="form-horizontal col-xs-5 text-left"><%= @wine.variety %></div>
  <div class="form-horizontal col-xs-2 text-right"><strong>Maturity</strong></div>
  <div class="form-horizontal col-xs-3 text-left"><%= @wine.maturity %></div>
</div>

<div class="row">
  <div class="form-horizontal col-xs-2 text-right"><strong>Vineyard</strong></div>
  <div class="form-horizontal col-xs-5 text-left"><%= @wine.vineyard %></div>
  <div class="form-horizontal col-xs-2 text-right"><strong>Drink By</strong></div>
  <div class="form-horizontal col-xs-3 text-left"><%= @wine.drink_by %></div>
</div>

<div class="row">
  <div class="form-horizontal col-xs-2 text-right"><strong>Appellation</strong></div>
  <div class="form-horizontal col-xs-5 text-left"><%= @wine.appellation %></div>
  <div class="form-horizontal col-xs-2 text-right"><strong>Alcohol</strong></div>
  <div class="form-horizontal col-xs-3 text-left"><%= @wine.alcohol_content + "%" if !@wine.alcohol_content.nil? %></div>
</div>

<div class="row">
  <div class="form-horizontal col-xs-2 text-right"><strong>Winemaker</strong></div>
  <div class="form-horizontal col-xs-5 text-left"><%= @wine.winemaker %></div>
  <div class="form-horizontal col-xs-2 text-right"><strong>Bottle Size</strong></div>
  <div class="form-horizontal col-xs-3 text-left"><%= @wine.bottle_size %></div>
</div>

<div class="row">
  <div class="form-horizontal col-xs-2 text-right"><strong>Color</strong></div>
  <div class="form-horizontal col-xs-5 text-left"><%= @wine.color %></div>
  <div class="form-horizontal col-xs-2 text-right"><strong>Sparkling</strong></div>
  <div class="form-horizontal col-xs-3 text-left"><%= @wine.sparkling ? "Yes" : "No" %></div>
</div>

<div class="row">
  <div class="form-horizontal col-xs-2 text-right"><strong>Country</strong></div>
  <div class="form-horizontal col-xs-5 text-left"><%= @wine.country %></div>
  <div class="form-horizontal col-xs-2 text-right"><strong>Dessert</strong></div>
  <div class="form-horizontal col-xs-3 text-left"><%= @wine.dessert  ? "Yes" : "No" %></div>
</div>

<div class="row">
  <div class="form-horizontal col-xs-6 text-center"><strong>My Notes</strong></div>
  <div class="form-horizontal col-xs-6 text-center"><strong>Other Notes</strong></div>
</div>

<div class="row">
  <div class="form-horizontal col-xs-6 text-left my-notes"><%= simple_format(@wine.my_notes) %></div>
  <div class="form-horizontal col-xs-6 text-left other-notes"><%= simple_format(@wine.other_notes) %></div>
</div>

<hr>
<h4>Bottles</h4>
<p>
  <%= pluralize(@wine.bottles.count, 'bottle') %>, <%= @available_bottles.count %> <%= 'available' %>
</p>


<div class="row">
  <div class="form-horizontal col-xs-2"><strong>From</strong></div>
  <div class="form-horizontal col-xs-1"><strong>Price</strong></div>
  <div class="form-horizontal col-xs-2"><strong>Location</strong></div>
  <div class="form-horizontal col-xs-2"><strong>Bought</strong></div>
  <div class="form-horizontal col-xs-1"><strong>Consumed</strong></div>
</div>

<% @wine.bottles.each do |bottle| %>
    <div class="row">
      <div class="form-horizontal col-xs-2"><%= bottle.purchased_from %></div>
      <div class="form-horizontal col-xs-1"><%= number_to_currency(bottle.purchase_price, precision: 2) %></div>
      <div class="form-horizontal col-xs-2"><%= bottle.location %></div>
      <div class="form-horizontal col-xs-2"><%= date_or_nil(bottle.purchase_date) %></div>
      <div class="form-horizontal col-xs-1"><%= bottle.consumed_date.nil? ? nil : bottle.consumed_date.strftime("%m/%d/%Y") %></div>
      <div class="form-horizontal col-xs-1"></div>
      <div class="form-horizontal col-xs-1 edit-bottle">
        <%= link_to 'Edit', [:edit, bottle.wine, bottle], method: :get %>
      </div>
      <div class="form-horizontal col-xs-1">
        <%= link_to 'Drink', bottles_drink_path(bottle), method: :put %>
      </div>
      <div class="form-horizontal col-xs-1">
        <%= link_to 'Delete', [bottle.wine, bottle], method: :delete,
                    data: {confirm: 'This will delete the bottle forever. "Drink"'\
                    ' will set the consumed date and clear the location. Are you sure you want to delete?'} %>
      </div>
    </div>
<% end %>

<hr>

<h4>Add a bottle:</h4>

<%= form_for ([@wine, @wine.bottles.build]) do |f| %>
    <div class="row">
      <div class="form-horizontal col-md-2"><strong>From</strong></div>
      <div class="form-horizontal col-md-2"><strong>Price</strong></div>
      <div class="form-horizontal col-md-2"><strong>Location</strong></div>
      <div class="form-horizontal col-md-2"><strong>Bought</strong></div>
      <div class="form-horizontal col-md-2"><strong>Consumed</strong></div>
    </div>

    <div class="row">
      <div class="form-horizontal col-md-2"><%= f.text_field :purchased_from, :style => "color:black" %></div>
      <div class="form-horizontal col-md-2"><%= f.number_field :purchase_price, :size => "9", :maxlength => "9",
                                                               :step => 0.01, :max => 99999.99, :style => "color:black",
                                                               :precision => number_with_precision(:purchase_price, :precision => 2) %>
      </div>
      <div class="form-horizontal col-md-2"><%= f.text_field :location, :style => "color:black" %></div>
      <div class="form-horizontal col-md-2"><%= f.date_field :purchase_date, options = {style: "height:26px"} %></div>
      <div class="form-horizontal col-md-2"><%= f.date_field :consumed_date, options = {style: "height:26px"} %></div>
      <br>
      <br>
    </div>

    <p>
      <button type="submit" class="btn btn-default btn-primary, style = black">
        Add Bottle
        <span class="glyphicon glyphicon-glass"></span>
      </button>

      <%= link_to edit_wine_path, class: "btn btn-default btn-primary, foreground = black" do %>
          Edit Wine
          <span class="glyphicon glyphicon-glass"></span>
      <% end %>

      <%= link_to wines_path, class: "btn btn-default btn-primary, foreground = black" do %>
          All Wines
          <span class="glyphicon glyphicon-glass"></span>
      <% end %>
    </p>
<% end %>